package com.qf.with_my_car.pojo;

import java.io.Serializable;

public class Vendor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.brandname
     *
     * @mbggenerated
     */
    private String brandname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.vendorname
     *
     * @mbggenerated
     */
    private String vendorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.vendorlogo
     *
     * @mbggenerated
     */
    private String vendorlogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendor.createtime
     *
     * @mbggenerated
     */
    private Integer createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vendor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.id
     *
     * @return the value of vendor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.id
     *
     * @param id the value for vendor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.brandname
     *
     * @return the value of vendor.brandname
     *
     * @mbggenerated
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.brandname
     *
     * @param brandname the value for vendor.brandname
     *
     * @mbggenerated
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.vendorname
     *
     * @return the value of vendor.vendorname
     *
     * @mbggenerated
     */
    public String getVendorname() {
        return vendorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.vendorname
     *
     * @param vendorname the value for vendor.vendorname
     *
     * @mbggenerated
     */
    public void setVendorname(String vendorname) {
        this.vendorname = vendorname == null ? null : vendorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.vendorlogo
     *
     * @return the value of vendor.vendorlogo
     *
     * @mbggenerated
     */
    public String getVendorlogo() {
        return vendorlogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.vendorlogo
     *
     * @param vendorlogo the value for vendor.vendorlogo
     *
     * @mbggenerated
     */
    public void setVendorlogo(String vendorlogo) {
        this.vendorlogo = vendorlogo == null ? null : vendorlogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendor.createtime
     *
     * @return the value of vendor.createtime
     *
     * @mbggenerated
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendor.createtime
     *
     * @param createtime the value for vendor.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brandname=").append(brandname);
        sb.append(", vendorname=").append(vendorname);
        sb.append(", vendorlogo=").append(vendorlogo);
        sb.append(", createtime=").append(createtime);
        sb.append("]");
        return sb.toString();
    }
}