package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.CarImage_bg;
import com.qf.with_my_car.pojo.CarImageExample_bg;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface CarImageMapper_bg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int countByExample(CarImageExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int deleteByExample(CarImageExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int insert(CarImage_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int insertSelective(CarImage_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    List<CarImage_bg> selectByExampleWithRowbounds(CarImageExample_bg example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    List<CarImage_bg> selectByExample(CarImageExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    CarImage_bg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarImage_bg record, @Param("example") CarImageExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarImage_bg record, @Param("example") CarImageExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarImage_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarImage_bg record);
}