package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.CarMake_bg;
import com.qf.with_my_car.pojo.CarMakeExample_bg;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface CarMakeMapper_bg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int countByExample(CarMakeExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int deleteByExample(CarMakeExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int insert(CarMake_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int insertSelective(CarMake_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    List<CarMake_bg> selectByExampleWithRowbounds(CarMakeExample_bg example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    List<CarMake_bg> selectByExample(CarMakeExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    CarMake_bg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarMake_bg record, @Param("example") CarMakeExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarMake_bg record, @Param("example") CarMakeExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarMake_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarMake_bg record);
}