package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.CarModel_bg;
import com.qf.with_my_car.pojo.CarModelExample_bg;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface CarModelMapper_bg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int countByExample(CarModelExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int deleteByExample(CarModelExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int insert(CarModel_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int insertSelective(CarModel_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    List<CarModel_bg> selectByExampleWithRowbounds(CarModelExample_bg example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    List<CarModel_bg> selectByExample(CarModelExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    CarModel_bg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarModel_bg record, @Param("example") CarModelExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarModel_bg record, @Param("example") CarModelExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarModel_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarModel_bg record);
}