package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberPoint_bg;
import com.qf.with_my_car.pojo.MemberPointExample_bg;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface MemberPointMapper_bg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int countByExample(MemberPointExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int deleteByExample(MemberPointExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int insert(MemberPoint_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int insertSelective(MemberPoint_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    List<MemberPoint_bg> selectByExampleWithRowbounds(MemberPointExample_bg example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    List<MemberPoint_bg> selectByExample(MemberPointExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    MemberPoint_bg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberPoint_bg record, @Param("example") MemberPointExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberPoint_bg record, @Param("example") MemberPointExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberPoint_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberPoint_bg record);
}