package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberCar_bg;
import com.qf.with_my_car.pojo.MemberCarExample_bg;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface MemberCarMapper_bg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int countByExample(MemberCarExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int deleteByExample(MemberCarExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int insert(MemberCar_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int insertSelective(MemberCar_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    List<MemberCar_bg> selectByExampleWithRowbounds(MemberCarExample_bg example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    List<MemberCar_bg> selectByExample(MemberCarExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    MemberCar_bg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberCar_bg record, @Param("example") MemberCarExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberCar_bg record, @Param("example") MemberCarExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberCar_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberCar_bg record);
}