package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.MemberFav_bg;
import com.qf.with_my_car.pojo.MemberFavExample_bg;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface MemberFavMapper_bg {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int countByExample(MemberFavExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int deleteByExample(MemberFavExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int insert(MemberFav_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int insertSelective(MemberFav_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    List<MemberFav_bg> selectByExampleWithRowbounds(MemberFavExample_bg example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    List<MemberFav_bg> selectByExample(MemberFavExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    MemberFav_bg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberFav_bg record, @Param("example") MemberFavExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberFav_bg record, @Param("example") MemberFavExample_bg example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberFav_bg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_fav
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberFav_bg record);
}