package com.qf.with_my_car.mapper;

import com.qf.with_my_car.pojo.Vendor;
import com.qf.with_my_car.pojo.VendorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface VendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int countByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int deleteByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int insert(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int insertSelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    List<Vendor> selectByExampleWithRowbounds(VendorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    List<Vendor> selectByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    Vendor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Vendor record);
}